version: '3'

services:
  web:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: baykar_db
      POSTGRES_USER: ozybo
      POSTGRES_PASSWORD: Q5LEhEaCz5LLRNZ
    ports:
      - "5432:5432"