# Generated by Django 5.1.3 on 2024-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team_type',
            field=models.CharField(choices=[('Kanat', 'Kanat Takımı'), ('Gövde', 'Gövde Takımı'), ('Kuyruk', 'Kuyruk Takımı'), ('Aviyonik', 'Aviyonik Takımı'), ('Montaj', 'Montaj Takımı')], max_length=8),
        ),
    ]
