# Generated by Django 5.1.3 on 2024-11-15 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_age_alter_customuser_team_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKI', 'AKINCI'), ('KIZ', 'KIZILELMA')], max_length=3, verbose_name='Uçak Tipi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('Kanat', 'Kanat'), ('Gövde', 'Gövde'), ('Kuyruk', 'Kuyruk'), ('Aviyonik', 'Aviyonik')], max_length=8, verbose_name='Parça Tipi')),
                ('plane_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKI', 'AKINCI'), ('KIZ', 'KIZILELMA')], max_length=3, verbose_name='Uçak Tipi')),
                ('mounted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
                ('plane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plane', verbose_name='Uçak')),
            ],
        ),
    ]
